meta_product_name: "Dragon's Hourglass"
meta_title: "Dragon's Hourglass - Slay your tasks, rule your time"
meta_description: "Embark on an enchanting journey with our fantasy-themed Pomodoro experience. Engage in a gamified approach to time management, where each task becomes a heroic quest. Boost your productivity and unleash your inner adventurer with our immersive and magical Pomodoro timer. Begin your quest now!"
meta_image: "cover.png"
